version: "3"
services:
  db:
    container_name: usResilienceDB
    image: postgis/postgis:12-3.0
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./data:/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  web:
    container_name: usResilienceApi
    build:
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    environment:
      POSTGRES_PORT_5432_TCP_ADDR: db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - .:/myapp
    ports:
      - "4000:3000"
    depends_on:
      - db
volumes:
  postgres-data:
